### ISSUE TITLE
captcha.py无法 run

### ISSUE THREAD

**Issue by 13275000508** [cjsworld/jlpt-bookseat#13]
captcha.py无法 run，显示line8 and line 9 “an unexpected keyword argument 'beta‘”

**Comment by cjsworld** [comment]
确认ddddocr是用的最新版本1.4.7。本身代码比较简单，建议自己研究下。有问题可以找 https://github.com/sml2h3/ddddocr

**Comment by 13275000508** [comment]
看了下https://github.com/sml2h3/ddddocr， 原来是不支持MacBook M1，用了另外一个自动识别插件了，谢谢
