### ISSUE TITLE
大佬帮我看看为什么第七行报错呢？

### ISSUE THREAD

**Issue by kll5201314** [cjsworld/jlpt-bookseat#14]
C:\Users\23749>python F:\jlpt\captcha.py
Traceback (most recent call last):
  File "F:\jlpt\captcha.py", line 8, in <module>
    ocr_beta = ddddocr.DdddOcr(beta=True, show_ad=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DdddOcr.__init__() got an unexpected keyword argument 'beta'

**Comment by cjsworld** [comment]
参考最新ReadMe，更新于 da06e03
