### ISSUE TITLE
你好，使用代码时提示WARNING: This is a development server. Do not use it in a production deployment.

### ISSUE THREAD

**Issue by ButtercatT** [cjsworld/jlpt-bookseat#17]
![image](https://github.com/cjsworld/jlpt-bookseat/assets/44700688/59b3a0b9-2966-4311-ad38-bbc090431a9e)

**Comment by ButtercatT** [comment]
使用pywsgi 进行替代后界面没有显示出来

**Comment by cjsworld** [comment]
这个只是警告，不是报错。flask内置了一个性能较弱的http服务器用于开发测试，不推荐在需要性能的生产环境中使用，但在此项目中，已足够使用。如果想要研究更多，可以看这里：https://zhuanlan.zhihu.com/p/488458470

另，python脚本是启动了一个http服务器，用于提供验证码识别服务。界面是需要把js代码放到浏览器控制台执行才会有。

**Comment by ButtercatT** [comment]
已经解决，非常感谢！
