### ISSUE TITLE
验证码OCR请求失败

### ISSUE THREAD

**Issue by CHINABBQ** [cjsworld/jlpt-bookseat#4]
已搭建依赖，请问自动识别验证码时，验证码OCR请求失败如何解决

**Comment by cjsworld** [comment]
需要搭建验证码识别服务，确认正在运行，并且脚本正确填入服务的url。

如果已经搭建了，可以在F12里的network看下请求的详细情况。

**Comment by CHINABBQ** [comment]
已搭建依赖，但不知如何查询服务的url

![_YA 6B5UF) R_G@)NO$PG~I](https://user-images.githubusercontent.com/117297817/226647667-71f1e9f1-36ba-4929-87e6-2636c57be145.png)

**Comment by cjsworld** [comment]
connect refused代表识别服务没有正常运行。

按照ReadMe最后提供的方法，安装环境和依赖，运行python脚本，确保过程中没有报错

**Comment by CHINABBQ** [comment]
全程没有报错，想请问下服务的url在哪里查看

**Comment by roiiiu** [comment]
> 全程没有报错，想请问下服务的url在哪里查看

使用127.0.0.1不要使用localhost试试

**Comment by CHINABBQ** [comment]
使用http://127.0.0.1/ocr 也是connect refused

**Comment by roiiiu** [comment]
> 使用http://127.0.0.1/ocr 也是connect refused

端口号5000

**Comment by valyria-Gao** [comment]
![4 R2)V)5 $80_RS}J45YQ6L](https://user-images.githubusercontent.com/77685991/226688216-41927bdf-c722-43d8-9e8f-4d9a40ed8698.png)
hhhhh遇到了问题

**Comment by valyria-Gao** [comment]
![E5F2A_25SDSCSI4TUW_ TH7](https://user-images.githubusercontent.com/77685991/226697470-55b4e9b7-5bab-4f5b-8023-5c0252983e83.png)
www
完蛋，还是不行

**Comment by CHINABBQ** [comment]
是诶，环境都搭好了，程序也运行了，但还是不行
![image](https://user-images.githubusercontent.com/117297817/226703630-f500d79d-8e3e-495a-8190-358404b74e2b.png)

**Comment by cjsworld** [comment]
> ![E5F2A_25SDSCSI4TUW_ TH7](https://user-images.githubusercontent.com/77685991/226697470-55b4e9b7-5bab-4f5b-8023-5c0252983e83.png) www 完蛋，还是不行

这个是已经启动了，但是因为没有带url参数，导致报错了。

url参数是验证码图片的地址，比如：`https://checkimage.neea.cn/302585E64F7A5247D27BA48B3940BEF4.jpg`

python服务启动之后，应该能在控制台看到如下输出：
```
 * Running on http://127.0.0.1:5000
```

在浏览器访问`http://localhost:5000/ocr?url=https://checkimage.neea.cn/302585E64F7A5247D27BA48B3940BEF4.jpg`，应该可以看到输出了识别结果`LxJJ`。

一切ok的话，需要填写到抢座脚本的地址是`http://localhost:5000/ocr`，url参数会由脚本自己加上。

**Comment by cjsworld** [comment]
> 全程没有报错，想请问下服务的url在哪里查看

如果你的python服务正常启动，能看到` * Running on http://127.0.0.1:5000`的输出，但是浏览器却访问不了，报connection refused的话，可以检查下防火墙，以及是否有安全软件拦截。

**Comment by CHINABBQ** [comment]
大佬，运行时出现这个怎么破
如果用python打开的话就是一闪而过，没有输出

发生异常: ImportError
DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。
  File "C:\Users\ASUS\Desktop\jlpt-bookseat-master\captcha.py", line 4, in <module>
    import ddddocr
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。

![image](https://user-images.githubusercontent.com/117297817/226784984-4ed0ba66-5218-49be-844e-ad312d169a2c.png)

**Comment by cjsworld** [comment]
> 大佬，运行时出现这个怎么破 如果用python打开的话就是一闪而过，没有输出
> 
> 发生异常: ImportError DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。 File "C:\Users\ASUS\Desktop\jlpt-bookseat-master\captcha.py", line 4, in import ddddocr ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的程序。
> 
> ![image](https://user-images.githubusercontent.com/117297817/226784984-4ed0ba66-5218-49be-844e-ad312d169a2c.png)

善于使用搜索来解决问题，而非遇到问题第一时间找人问

https://blog.csdn.net/zhuchengchengct/article/details/124854199

**Comment by CHINABBQ** [comment]
感谢大佬，之前已经查询到此方法，并已安装08-22年版本，但还是出错，很伤脑筋T-T
![image](https://user-images.githubusercontent.com/117297817/226788009-f430e60a-1f45-40e3-91e5-5a599cfbe1b0.png)

**Comment by cjsworld** [comment]
报错信息是无法加载onnxruntime_pybind11_state.dll的库，建议如下排查：

1. 检查python的site-packages目录里，onnxruntime下面有没有onnxruntime_pybind11_state.dll。
2. 如果文件存在，有可能是dll相关的依赖缺失，比如c++运行库、显卡驱动相关。
3. 你安装的是vc2015-2022，也许可以按照网上提示的，装个vc2019尝试一下。
4. 实在搞不定，且有条件的情况下，可以装个Ubuntu虚拟机，在里面跑python程序。

**Comment by CHINABBQ** [comment]
尝试重新安装python，搭建依赖后成功了，感谢大佬耐心指导

**Comment by valyria-Gao** [comment]
> > ![E5F2A_25SDSCSI4TUW_ TH7](https://user-images.githubusercontent.com/77685991/226697470-55b4e9b7-5bab-4f5b-8023-5c0252983e83.png) www 完蛋，还是不行
> 
> 这个是已经启动了，但是因为没有带url参数，导致报错了。
> 
> url参数是验证码图片的地址，比如：`https://checkimage.neea.cn/302585E64F7A5247D27BA48B3940BEF4.jpg`
> 
> python服务启动之后，应该能在控制台看到如下输出：
> 
> ```
>  * Running on http://127.0.0.1:5000
> ```
> 
> 在浏览器访问`http://localhost:5000/ocr?url=https://checkimage.neea.cn/302585E64F7A5247D27BA48B3940BEF4.jpg`，应该可以看到输出了识别结果`LxJJ`。
> 
> 一切ok的话，需要填写到抢座脚本的地址是`http://localhost:5000/ocr`，url参数会由脚本自己加上。

那我现在测试的话，还没有到时间，第一次验证码需要自己手动输入，之后到时间了才能自动识别填写是吗？我打开你提供的网址`http://localhost:5000/ocr?url=https://checkimage.neea.cn/302585E64F7A5247D27BA48B3940BEF4.jpg`雀食看到了识别结果

**Comment by cjsworld** [comment]
你可以把脚本里startHour，startMinite改掉用于测试
