### ISSUE TITLE
验证显示失败

### ISSUE THREAD

**Issue by Gator926** [cjsworld/jlpt-bookseat#5]
已经测试过360、qq、chrome验证码均显示失败，麻烦请问下那种浏览器可以正常显示验证码？

**Comment by cjsworld** [comment]
现在的脚本已更新，不再需要控制台显示验证码，采用内嵌界面的形式处理了

**Comment by Gator926** [comment]
您好，这是自动回复，我已收到您的邮件，我会尽快给您回复。Hello, I received your e-mail. I will reply soon.

**Comment by Gator926** [comment]
> 现在的脚本已更新，不再需要控制台显示验证码，采用内嵌界面的形式处理了

您好，我脚本放在控制台运行后，UI上验证码仍然无法显示，请问下如何解决呢？
![微信截图_20230322125320](https://user-images.githubusercontent.com/13447457/226805563-8d82a927-be0a-4882-9b90-0f49bc2be461.png)

**Comment by cjsworld** [comment]
验证码是过程中需要才会出现，并非一直显示

**Comment by veserise** [comment]
> 验证码是过程中需要才会出现，并非一直显示

麻烦再请教一下，去年的JS是否仍然可以运行呢？

**Comment by Gator926** [comment]
感谢，已经解决，成功抢到
