### ISSUE TITLE
会话已过期或者验证码已过期

### ISSUE THREAD

**Issue by cjsworld** [cjsworld/jlpt-bookseat#7]
怀疑JLPT报名网站的登录状态可能用的redis之类的，且容量不够大，当访问人多压力大的时候，会按照时间淘汰之前的数据，导致会话状态过期，或者验证码状态过期。

这玩意手动去抢，简直是噩梦。

解决方法：
1、验证码过期会自动重新尝试，自动识别，问题不大。
2、会话状态过期比较头疼，会掉到重新登陆页面。最好把登陆流程也做到自动化，会话过期直接自动重新登陆。

额。。本来只是想做个简单工具，越做越复杂了。。。反正我报上了，没啥动力继续改。。。

**Comment by Gator926** [comment]
刚才也遇到了这个问题，验证码一直过期一度怀疑人生了，已经很好用了，感谢感谢

**Comment by noah19846** [comment]
没有这个脚本根本不敢想手动如何能抢上，十分感谢！

**Comment by CHINABBQ** [comment]
十分感谢，成功抢上了

**Comment by umaYnit** [comment]
手动丑陋的补了重新登录的部分，不知道怎么测试，大佬能帮忙看一下么
[jlpt.txt](https://github.com/cjsworld/jlpt-bookseat/files/11037871/jlpt.txt)

**Comment by cjsworld** [comment]
已完成
14c138b
